Repository NCAR/geocat-viz, pull requests merged in 2022-04, with the labels that each got.

#60 Added installation.rst
  INSTALLATION.md
  docs/index.rst
  docs/installation.rst
Labels: documentation, ready for review

#40 NCL_Plot Update
  .gitignore
  conda_environment.yml
  requirements.txt
  src/geocat/viz/__init__.py
  src/geocat/viz/contourf/__init__.py
  src/geocat/viz/contourf/_plot_util.py
  src/geocat/viz/contourf/contourf.py
  src/geocat/viz/plot_classes/__init__.py
  src/geocat/viz/plot_classes/_plot_util.py
  src/geocat/viz/plot_classes/contourf.py
  src/geocat/viz/plot_classes/taylor.py
  src/geocat/viz/taylor/__init__.py
Labels: ready for review

#63 GeoCAT-viz documentation fix
  .readthedocs.yml
Labels: bug

#50 Populate docs
  .readthedocs.yml
  CONTRIBUTING.md
  ci/environment.yml
  docs/_static/images/nsf.png
  docs/_static/theme_overrides.css
  docs/_templates/autosummary/class.rst
  docs/api.rst
  docs/citation.rst
  docs/conf.py
  docs/examples.rst
  docs/index.rst
  docs/internal_api/index.rst
  docs/support.rst
  docs/user_api/index.rst
  setup.py
  src/geocat/viz/contourf.py
  src/geocat/viz/taylor.py
  src/geocat/viz/util.py
Labels: ready for review

#64 Automation
  .github/workflows/upstream-examples-ci.yml
Labels: enhancement, developer feature, ready for review
