Repository NCAR/geocat-viz, pull requests merged in 2024-03, with the labels that each got.

#219 Documentation improvement for TaylorDiagram class and set_titles_and_labels
  .gitignore
  docs/examples/taylor.ipynb
  docs/release-notes.rst
  src/geocat/viz/taylor.py
  src/geocat/viz/util.py
Labels: documentation

#230 Update release notes for v2024.03.0
  docs/release-notes.rst
Labels: release

#232 Clean up CI
  .github/workflows/ci.yml
  docs/release-notes.rst
Labels: developer feature
