Repository NCAR/geocat-viz, pull requests merged in 2024-02, with the labels that each got.

#194 Python 3.12 support and Windows and M1 testing
  .github/workflows/ci.yml
  build_envs/docs.yml
  build_envs/environment.yml
  docs/release-notes.rst
  setup.cfg
Labels: enhancement, developer feature

#196 Add Dependabot
  .github/dependabot.yml
Labels: developer feature

#205 Update release notes for v2024.02.0 release
  docs/release-notes.rst
Labels: release

#208 PypI Trusted Publishing
  .github/workflows/pypi.yaml
  docs/release-notes.rst
Labels: enhancement, developer feature, ready for review, release

#207 Fix Taylor diagram annotate_on issue
  docs/release-notes.rst
  src/geocat/viz/taylor.py
Labels: bug

#218 Configure link checker to ignore problematic sites and add a CI badge to the package README
  README.md
  docs/conf.py
  docs/release-notes.rst
Labels: documentation, developer feature

#222 Update release-notes.rst for v2024.02.1 release
  docs/release-notes.rst
Labels: release
